apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: snapshot-api-objects
spec:
  version: "v0.0.6"
  homepage: https://github.com/oguzhan-yilmaz/kubectl-snapshot-api-objects
  shortDescription: "Snapshot Kubernetes API Objects"
  description: |
    Snapshot all Kubernetes Objects and save them as yaml files in .tar.gz archive.
  caveats: |
    Requires:
      - kubectl neat
  platforms:
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - darwin
        - linux
    uri: "https://github.com/oguzhan-yilmaz/kubectl-snapshot-api-objects/archive/v0.0.6.tar.gz"  # https://github.com/achanda/kubectl-restart/archive/v0.0.3.zip
    sha256: 39ee15d3852056ac870769c37cb83880546b2fbda1e58731b34d3d7b49bb2380
    files:
    - from: "kubectl-snapshot-api-objects-*/snapshot-api-objects"
      to: "."
    - from: "kubectl-snapshot-api-objects-*/LICENSE"
      to: "."
    bin: snapshot-api-objects

    # chmod +x ~/.krew/store/snapshot-api-objects/v0.0.1/source/snapshot-api-objects-script.sh